## Lecture 1: Introduction
- Software group do courses on CUDA and cloud computing, useful to ask if I need help: rse.ox.ac.uk, can sign onto courses.

- Software is important for reproducibility

- Difference between programming and engineering: programming is algorithms, syntax, individual, one line at a time. Engineering considers the life cycle of the software, maintenance, refactoring, considering stakeholders, building for the future etc.

- Waterfall model:
    - requirement analysis
    - design
    - implementation
    - testing
    - release
    - maintenance
not so useful in academia as too fixed, agile model turns this into a loop and attempts to make the minimum viable product, the requirements are always assessed and reconsidered.

- Recommended book: facts and fallacies of software engineering

- All training on https://train.rse.ox.ac.uk/


- Notes for myself:
    - try to include unit testing
    - use WSl from day 1
    - how to include pseudo code in quarto
    - learn about testing during programme



## Virtual Environments
To create a virtual environment, type 

```bash
python3 -m venv {desired name of venv}
source {desired name of venv}/bin/activate
```

The first line of code creates the virtual environment. It makes a folder in the cwd that contains all the info and libraries regarding the virtual environment. The second line of code actually activates the virtual environment.

To deactivate the virtual environment, type:
```bash
deactivate
```

To delete a virtual environment, move into the directory containing its folder and type
```bash
rm -r {name of venv}
```



### Testing style for pseudo code
<details>
<summary>Pseudocode</summary>

```bash
cat vcf_file | sed -n '/#CHROM/,$p' | cut -f 1,2,4,5 > variant_info.txt 
```

</details>

